accounts/urls.py
from django.urls import path  # path('url', 'function')
from . import views

app_name = "accounts"
urlpatterns = [  
    path('signup', views.signUp, name="signup"),
    path('Login', views.Login, name="Login"),
    path('Logout', views.Logout, name="Logout"),
]

articels/urls.py
from django.urls import path  # path('url', 'function')
from . import views

app_name = "articel"
urlpatterns = [  
    path('', views.articelsList, name="List"),
    path('create', views.CreateArticle, name="Create"),
    path('create/', views.CreateArticle, name="Create"),
    path('<slug>', views.articelDetial, name="Detial"),
]

djongoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from articels.views import articelsList

urlpatterns = [
    path('admin/', admin.site.urls),  # path('url', 'function')
    path('about/', views.about),
    path('articels/', include('articels.urls')), # include('urls file in other app')
    path('NotFound/', views.NotFound),
    path('accounts/', include('accounts.urls')),
    path('', articelsList),

]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articels/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Articel(models.Model):
    title = models.CharField(max_length=100)
    slog = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    Image = models.ImageField(default="default.jpg", blank = True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    # Return in Admin title alternative object
    def __str__(self):
        return self.title
    
    def snippet(self):
        if (len(self.body) > 50):
            return self.body[:50] + "..."
        else:
            return self.body

articels/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    
    class Meta:
        model = models.Articel
        fields = ["title", "slog", "body", "Image"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as jng_Login
from django.contrib.auth import logout as jng_logout

# Create your views here.

# Login
def signUp(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #Login
            user = form.save() #Register then get user
            jng_Login(request, user)
            return redirect('articel:List')
    else :  
        form = UserCreationForm()
    return render(request, GetViewName('signUp'), {"form":form})

def Login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Login
            user = form.get_user()
            jng_Login(request, user)
            
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else: 
                return redirect('articel:List')
    else:
        form = AuthenticationForm()
    return render(request, GetViewName('Login'), {"form":form})

def Logout(request):
    if request.method == 'POST':
        jng_logout(request)
    return redirect('articel:List')

# Return Name of View 
def GetViewName(functionName:str)->str:
    return f"accounts/{functionName}.html"

articels/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models # import models
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
# request paramter for django and most be here

def articelsList(request):
    articels = models.Articel.objects.all().order_by('-date') # get all models and sort by date
    args = {"articels" : articels} # Se t Model in args to send to view
    return render(request, GetViewName('articelsList'), args)

def articelDetial(request, slug):
    # return HttpResponse(slug)
    articel = models.Articel.objects.get(slog = slug)
    args = {"articel" : articel} # Set Model in args to send to view
    return render(request, GetViewName('articelDetial'), args)


@login_required(login_url = "/accounts/Login")
def CreateArticle(request):
    if (request.method == 'POST'):
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid:
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('articel:List')
    else:
        form = forms.CreateArticle()
        return render(request, GetViewName('CreateArticle'), {"form": form})

# Return Name of View 
def GetViewName(functionName:str)->str:
    return f"articels/{functionName}.html"

djongoBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    # return HttpResponse("Hello Django!\nIm Sadeq Nice to meet you.")
    return render(request, 'about.html')


def home(request):
    # return HttpResponse("Hello Django!\nIt's Your New Home.")
        return render(request, 'home.html')

def NotFound(request):
    # return HttpResponse("Hello Django!\nIt's NotFound 404-Error.")
        return render(request, 'NotFound.html')

accounts/templates/accounts/Login.html
{% extends 'base.html' %}
{% block content %}
<form class="site-form" action="{% url 'accounts:Login' %}" method="post">
    <h1>Login</h1>
{{form}}
{% csrf_token %}
{% if request.GET.next %}
    <input type="hidden" name="next" value={{ request.GET.next }}/>
{% endif %}
<input type="submit" value="Login">

</form>
{% endblock content %}

accounts/templates/accounts/signUp.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign Up</h1>

<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
{{form}}

{% csrf_token %}
<input type="submit" value="Signup">

</form>
 {% endblock content %}

articels/templates/articels/CreateArticle.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="createArticle">
<h1>
    Create Article
</h1>
<form class="site-form" action="{% url 'articel:Create' %}" method="post" enctype="multpart/form-data">
{{ form }}
{% csrf_token %}
<input type="submit" name="" value="create"/>
</form>
</div>
<script src="{% static 'slugify.js' %}"></script>
{% endblock content %}

articels/templates/articels/articelDetial.html
{% extends 'base.html' %}

{% block title %} Articel {% endblock title %}

{% block content %}
    <div class="article_detial">
        <div class="article" style="text-align:center;">
            <img src="{{articel.Image.url}}">
            <hr>
            <h3>{{ articel.title }}</h3>
    <br>
            <p>{{ articel.body }}</p>
        <br>
        <p class="creatdate">{{ articel.date }}</p>
        <p class='author'>Added by {{articel.author.username}}</p>
        </div>
    </div>
{% endblock content %}

articels/templates/articels/articelsList.html
{% extends 'base.html' %}
{% block title %} Articles {% endblock title %}
       
{% comment %} We use {% %} to coding like if, for{% endcomment %}
{% comment %} We use {{ }} to Get Data {% endcomment %}

{% block content %}
    <h1>Articels List</h1>
<div class='articles'>
    {% for i in articels %}
    <div class='article'>
        <h2><a href="{% url 'articel:Detial' slug=i.slog %}">{{i.title}}</a></h2>
        <p>{{i.snippet}}</p>
        <p class='author'>Added by {{i.author.username}}</p>
        <p>{{i.date}}</p>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>About us</title>
    </head>
    <body>
       <h1>About</h1>
       <p>Im Sadeq and I Learn Django</p>
    </body>
</html>

templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
<header>
    <h1>
        <a href="{% url 'articel:List' %}">@ LOGO @</a>
    </h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <span>Welcome {{ user.username }} !</span>
            </li>
            <li>
                <form class="logout-link" action="{% url 'accounts:Logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Logout">
                </form>
            </li>
            <li>
                <a class="highlight" href = "{% url 'articel:Create' %}"> Create New Article </a>
            </li>
            {% else %}
            <li>
                <a href = "{% url 'accounts:Login' %}"> Login </a>
            </li>
            <li>
                <a href = "{% url 'accounts:signup' %}"> Signup </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</header>
        <div class="wrapper">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Home</title>
    </head>
    <body>
       <h1>Home</h1>
       <p>Welcome to my Blog</p>
    </body>
</html>